param(
  [string]$TwentyUrl = "http://192.168.100.11:3000",
  [string]$RemoteName = "mikoton-target",
  [string]$Version
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

function Fail([string]$Message) {
  Write-Error $Message
  exit 1
}

function Load-DotEnv {
  $envPath = Join-Path (Get-Location) ".env"

  if (-not (Test-Path -LiteralPath $envPath)) {
    return
  }

  Get-Content -LiteralPath $envPath | ForEach-Object {
    $line = $_.Trim()

    if ($line -eq "" -or $line.StartsWith("#")) {
      return
    }

    $separatorIndex = $line.IndexOf("=")

    if ($separatorIndex -le 0) {
      return
    }

    $name = $line.Substring(0, $separatorIndex).Trim()
    $value = $line.Substring($separatorIndex + 1).Trim().Trim('"').Trim("'")

    if ($name -ne "") {
      Set-Item -Path "Env:$name" -Value $value
    }
  }
}

function Require-Command([string]$Name) {
  if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) {
    Fail "Required command not found: $Name"
  }
}

function Invoke-Checked([string]$FilePath, [string[]]$Arguments) {
  $displayArguments = @()

  for ($index = 0; $index -lt $Arguments.Length; $index++) {
    $displayArguments += $Arguments[$index]

    if ($Arguments[$index] -eq "--api-key" -and $index + 1 -lt $Arguments.Length) {
      $index += 1
      $displayArguments += "***"
    }
  }

  Write-Host "> $FilePath $($displayArguments -join ' ')"
  & $FilePath @Arguments

  if ($LASTEXITCODE -ne 0) {
    Fail "Command failed with exit code $LASTEXITCODE`: $FilePath"
  }
}

function Get-PackageJson {
  $packagePath = Join-Path (Get-Location) "package.json"

  if (-not (Test-Path -LiteralPath $packagePath)) {
    Fail "Run this script from mikoton-commercial-proposals"
  }

  return Get-Content -Raw -LiteralPath $packagePath | ConvertFrom-Json
}

function Get-ClientConfigVersion([string]$BaseUrl) {
  $config = Invoke-RestMethod -Uri "$BaseUrl/client-config" -Method Get

  if ($config.PSObject.Properties.Name -contains "version" -and $null -ne $config.version) {
    return [string]$config.version
  }

  if ($config.PSObject.Properties.Name -contains "serverVersion" -and $null -ne $config.serverVersion) {
    return [string]$config.serverVersion
  }

  if (
    $config.PSObject.Properties.Name -contains "data" -and
    $null -ne $config.data -and
    $config.data.PSObject.Properties.Name -contains "version" -and
    $null -ne $config.data.version
  ) {
    return [string]$config.data.version
  }

  return ""
}

function Assert-TarballContents([string]$TarballPath) {
  $entries = & tar -tzf $TarballPath

  if ($LASTEXITCODE -ne 0) {
    Fail "Unable to inspect tarball: $TarballPath"
  }

  if (-not ($entries | Select-String -SimpleMatch "manifest.json")) {
    Fail "Tarball does not contain manifest.json"
  }

  if (-not ($entries | Select-String -SimpleMatch "front-components")) {
    Fail "Tarball does not contain front component bundle"
  }

  if (-not ($entries | Select-String -SimpleMatch "logic-functions")) {
    Fail "Tarball does not contain logic function bundle"
  }

  if ($entries | Select-String -Pattern '(^|/)\.env($|\.|/)') {
    Fail "Tarball contains .env files"
  }

  if ($entries | Select-String -Pattern '\.map$') {
    Write-Warning "Tarball contains source maps generated by twenty-sdk 2.20.0"
  }
}

Load-DotEnv

Require-Command "node"
Require-Command "yarn.cmd"
Require-Command "git"
Require-Command "tar"

$package = Get-PackageJson

if ($package.name -ne "mikoton-commercial-proposals") {
  Fail "Unexpected package name: $($package.name)"
}

if (-not $env:TWENTY_API_KEY) {
  Fail "TWENTY_API_KEY must be set in the environment or local .env"
}

if ($Version -and $Version -ne $package.version) {
  Fail "Version parameter ($Version) does not match package.json ($($package.version))"
}

if (-not ($package.version -match '^\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?$')) {
  Fail "package.json version is not valid SemVer: $($package.version)"
}

$health = Invoke-RestMethod -Uri "$TwentyUrl/healthz" -Method Get

if ($health.status -ne "ok") {
  Fail "Twenty health check failed"
}

$serverVersion = Get-ClientConfigVersion -BaseUrl $TwentyUrl

if ($serverVersion -ne "v2.20.0" -and $serverVersion -ne "2.20.0") {
  Fail "Unsupported Twenty version '$serverVersion'. Expected v2.20.0"
}

$gitStatus = & git status --porcelain

if ($LASTEXITCODE -ne 0) {
  Fail "git status failed"
}

if ($gitStatus) {
  Fail "Git working tree must be clean before private deployment"
}

$commitSha = (& git rev-parse HEAD).Trim()

Invoke-Checked "yarn.cmd" @("install", "--immutable")
Invoke-Checked "yarn.cmd" @("lint")
Invoke-Checked "yarn.cmd" @("typecheck")
Invoke-Checked "yarn.cmd" @("test:unit")
Invoke-Checked "yarn.cmd" @("twenty", "dev:build", "--tarball", ".")

$tarball = Get-ChildItem -Path ".twenty\output" -Filter "*.tgz" -Recurse |
  Sort-Object LastWriteTime -Descending |
  Select-Object -First 1

if ($null -eq $tarball) {
  Fail "No .tgz tarball was created"
}

if ($tarball.Length -le 0) {
  Fail "Tarball is empty: $($tarball.FullName)"
}

Assert-TarballContents -TarballPath $tarball.FullName

$hash = Get-FileHash -Path $tarball.FullName -Algorithm SHA256
$builtAt = (Get-Date).ToUniversalTime().ToString("o")

New-Item -ItemType Directory -Path "release-artifacts" -Force | Out-Null

$releaseManifest = [ordered]@{
  appName = $package.name
  version = $package.version
  commitSha = $commitSha
  fileName = $tarball.Name
  sha256 = $hash.Hash.ToLowerInvariant()
  sizeBytes = $tarball.Length
  builtAt = $builtAt
  twentyUrl = $TwentyUrl
  twentyVersion = $serverVersion
}

$manifestPath = Join-Path "release-artifacts" "release-$($package.version).json"
$releaseManifest | ConvertTo-Json -Depth 4 | Set-Content -LiteralPath $manifestPath -Encoding UTF8

Write-Host "Tarball: $($tarball.FullName)"
Write-Host "Size: $($tarball.Length) bytes"
Write-Host "SHA-256: $($hash.Hash.ToLowerInvariant())"
Write-Host "Release manifest: $manifestPath"

Invoke-Checked "yarn.cmd" @(
  "twenty",
  "remote:add",
  "--as",
  $RemoteName,
  "--url",
  $TwentyUrl,
  "--api-key",
  $env:TWENTY_API_KEY
)

Invoke-Checked "yarn.cmd" @("twenty", "app:publish", "--private", "-r", $RemoteName, ".")
Invoke-Checked "yarn.cmd" @("twenty", "app:install", "-r", $RemoteName, ".")

Write-Host "Private deployment completed for $($package.name)@$($package.version)"
