import { defineIndex } from 'twenty-sdk/define';
import { COMMERCIAL_PROPOSAL_ITEM_FIELD_COMMERCIAL_PROPOSAL_UNIVERSAL_IDENTIFIER, COMMERCIAL_PROPOSAL_ITEM_INDEX_PARENT_UNIVERSAL_IDENTIFIER, COMMERCIAL_PROPOSAL_ITEM_OBJECT_UNIVERSAL_IDENTIFIER } from 'src/constants/universal-identifiers';

export default defineIndex({
  universalIdentifier: COMMERCIAL_PROPOSAL_ITEM_INDEX_PARENT_UNIVERSAL_IDENTIFIER,
  objectUniversalIdentifier: COMMERCIAL_PROPOSAL_ITEM_OBJECT_UNIVERSAL_IDENTIFIER,
  indexType: 'BTREE',
  fields: [{ universalIdentifier: '13797096-584c-4071-8313-22db4fdf64e7', fieldUniversalIdentifier: COMMERCIAL_PROPOSAL_ITEM_FIELD_COMMERCIAL_PROPOSAL_UNIVERSAL_IDENTIFIER }],
});
