import { defineIndex } from 'twenty-sdk/define';
import { COMMERCIAL_PROPOSAL_FIELD_IDEMPOTENCY_KEY_UNIVERSAL_IDENTIFIER, COMMERCIAL_PROPOSAL_INDEX_IDEMPOTENCY_UNIVERSAL_IDENTIFIER, COMMERCIAL_PROPOSAL_OBJECT_UNIVERSAL_IDENTIFIER } from 'src/constants/universal-identifiers';

export default defineIndex({
  universalIdentifier: COMMERCIAL_PROPOSAL_INDEX_IDEMPOTENCY_UNIVERSAL_IDENTIFIER,
  objectUniversalIdentifier: COMMERCIAL_PROPOSAL_OBJECT_UNIVERSAL_IDENTIFIER,
  indexType: 'BTREE',
  isUnique: true,
  fields: [{ universalIdentifier: 'b315c80a-8631-4213-9168-792f05f94ba3', fieldUniversalIdentifier: COMMERCIAL_PROPOSAL_FIELD_IDEMPOTENCY_KEY_UNIVERSAL_IDENTIFIER }],
});
