import { defineIndex } from 'twenty-sdk/define';
import { COMMERCIAL_PROPOSAL_ITEM_FIELD_CLIENT_KEY_UNIVERSAL_IDENTIFIER, COMMERCIAL_PROPOSAL_ITEM_INDEX_CLIENT_KEY_UNIVERSAL_IDENTIFIER, COMMERCIAL_PROPOSAL_ITEM_OBJECT_UNIVERSAL_IDENTIFIER } from 'src/constants/universal-identifiers';

export default defineIndex({
  universalIdentifier: COMMERCIAL_PROPOSAL_ITEM_INDEX_CLIENT_KEY_UNIVERSAL_IDENTIFIER,
  objectUniversalIdentifier: COMMERCIAL_PROPOSAL_ITEM_OBJECT_UNIVERSAL_IDENTIFIER,
  indexType: 'BTREE',
  fields: [{ universalIdentifier: '6e61b28e-a1da-46e3-9c34-7e9274eb791f', fieldUniversalIdentifier: COMMERCIAL_PROPOSAL_ITEM_FIELD_CLIENT_KEY_UNIVERSAL_IDENTIFIER }],
});
