import { defineIndex } from 'twenty-sdk/define';
import { COMMERCIAL_PROPOSAL_STAGE_FIELD_COMMERCIAL_PROPOSAL_UNIVERSAL_IDENTIFIER, COMMERCIAL_PROPOSAL_STAGE_INDEX_PARENT_UNIVERSAL_IDENTIFIER, COMMERCIAL_PROPOSAL_STAGE_OBJECT_UNIVERSAL_IDENTIFIER } from 'src/constants/universal-identifiers';

export default defineIndex({
  universalIdentifier: COMMERCIAL_PROPOSAL_STAGE_INDEX_PARENT_UNIVERSAL_IDENTIFIER,
  objectUniversalIdentifier: COMMERCIAL_PROPOSAL_STAGE_OBJECT_UNIVERSAL_IDENTIFIER,
  indexType: 'BTREE',
  fields: [{ universalIdentifier: 'c75c264d-d9e4-4150-ae5f-0255f19e8fb6', fieldUniversalIdentifier: COMMERCIAL_PROPOSAL_STAGE_FIELD_COMMERCIAL_PROPOSAL_UNIVERSAL_IDENTIFIER }],
});
