import { defineIndex } from 'twenty-sdk/define';

import {
  COMMERCIAL_PROPOSAL_FIELD_COMPANY_UNIVERSAL_IDENTIFIER,
  COMMERCIAL_PROPOSAL_FIELD_IDEMPOTENCY_KEY_UNIVERSAL_IDENTIFIER,
  COMMERCIAL_PROPOSAL_FIELD_NUMBER_UNIVERSAL_IDENTIFIER,
  COMMERCIAL_PROPOSAL_FIELD_OPPORTUNITY_UNIVERSAL_IDENTIFIER,
  COMMERCIAL_PROPOSAL_FIELD_STATUS_UNIVERSAL_IDENTIFIER,
  COMMERCIAL_PROPOSAL_INDEX_COMPANY_UNIVERSAL_IDENTIFIER,
  COMMERCIAL_PROPOSAL_INDEX_IDEMPOTENCY_UNIVERSAL_IDENTIFIER,
  COMMERCIAL_PROPOSAL_INDEX_NUMBER_UNIVERSAL_IDENTIFIER,
  COMMERCIAL_PROPOSAL_INDEX_OPPORTUNITY_UNIVERSAL_IDENTIFIER,
  COMMERCIAL_PROPOSAL_INDEX_STATUS_UNIVERSAL_IDENTIFIER,
  COMMERCIAL_PROPOSAL_ITEM_FIELD_CLIENT_KEY_UNIVERSAL_IDENTIFIER,
  COMMERCIAL_PROPOSAL_ITEM_FIELD_COMMERCIAL_PROPOSAL_UNIVERSAL_IDENTIFIER,
  COMMERCIAL_PROPOSAL_ITEM_INDEX_CLIENT_KEY_UNIVERSAL_IDENTIFIER,
  COMMERCIAL_PROPOSAL_ITEM_INDEX_PARENT_UNIVERSAL_IDENTIFIER,
  COMMERCIAL_PROPOSAL_ITEM_OBJECT_UNIVERSAL_IDENTIFIER,
  COMMERCIAL_PROPOSAL_STAGE_FIELD_CLIENT_KEY_UNIVERSAL_IDENTIFIER,
  COMMERCIAL_PROPOSAL_STAGE_FIELD_COMMERCIAL_PROPOSAL_UNIVERSAL_IDENTIFIER,
  COMMERCIAL_PROPOSAL_STAGE_INDEX_CLIENT_KEY_UNIVERSAL_IDENTIFIER,
  COMMERCIAL_PROPOSAL_STAGE_INDEX_PARENT_UNIVERSAL_IDENTIFIER,
  COMMERCIAL_PROPOSAL_STAGE_OBJECT_UNIVERSAL_IDENTIFIER,
  COMMERCIAL_PROPOSAL_OBJECT_UNIVERSAL_IDENTIFIER,
} from 'src/constants/universal-identifiers';

export const commercialProposalNumberIndex = defineIndex({
  universalIdentifier: COMMERCIAL_PROPOSAL_INDEX_NUMBER_UNIVERSAL_IDENTIFIER,
  objectUniversalIdentifier: COMMERCIAL_PROPOSAL_OBJECT_UNIVERSAL_IDENTIFIER,
  indexType: 'BTREE',
  isUnique: true,
  fields: [
    {
      universalIdentifier: 'cae84ee1-3408-4215-9cf8-d910adafd631',
      fieldUniversalIdentifier:
        COMMERCIAL_PROPOSAL_FIELD_NUMBER_UNIVERSAL_IDENTIFIER,
    },
  ],
});

export const commercialProposalStatusIndex = defineIndex({
  universalIdentifier: COMMERCIAL_PROPOSAL_INDEX_STATUS_UNIVERSAL_IDENTIFIER,
  objectUniversalIdentifier: COMMERCIAL_PROPOSAL_OBJECT_UNIVERSAL_IDENTIFIER,
  indexType: 'BTREE',
  fields: [
    {
      universalIdentifier: '5f7ba1bc-9625-470c-a412-e25a3604013a',
      fieldUniversalIdentifier:
        COMMERCIAL_PROPOSAL_FIELD_STATUS_UNIVERSAL_IDENTIFIER,
    },
  ],
});

export const commercialProposalOpportunityIndex = defineIndex({
  universalIdentifier:
    COMMERCIAL_PROPOSAL_INDEX_OPPORTUNITY_UNIVERSAL_IDENTIFIER,
  objectUniversalIdentifier: COMMERCIAL_PROPOSAL_OBJECT_UNIVERSAL_IDENTIFIER,
  indexType: 'BTREE',
  fields: [
    {
      universalIdentifier: 'c233e4ed-83f8-4df2-87a5-d187f8379000',
      fieldUniversalIdentifier:
        COMMERCIAL_PROPOSAL_FIELD_OPPORTUNITY_UNIVERSAL_IDENTIFIER,
    },
  ],
});

export const commercialProposalCompanyIndex = defineIndex({
  universalIdentifier: COMMERCIAL_PROPOSAL_INDEX_COMPANY_UNIVERSAL_IDENTIFIER,
  objectUniversalIdentifier: COMMERCIAL_PROPOSAL_OBJECT_UNIVERSAL_IDENTIFIER,
  indexType: 'BTREE',
  fields: [
    {
      universalIdentifier: '1f4d4f76-03f9-453a-a123-a07958d7033b',
      fieldUniversalIdentifier:
        COMMERCIAL_PROPOSAL_FIELD_COMPANY_UNIVERSAL_IDENTIFIER,
    },
  ],
});

export const commercialProposalIdempotencyIndex = defineIndex({
  universalIdentifier:
    COMMERCIAL_PROPOSAL_INDEX_IDEMPOTENCY_UNIVERSAL_IDENTIFIER,
  objectUniversalIdentifier: COMMERCIAL_PROPOSAL_OBJECT_UNIVERSAL_IDENTIFIER,
  indexType: 'BTREE',
  isUnique: true,
  fields: [
    {
      universalIdentifier: 'b315c80a-8631-4213-9168-792f05f94ba3',
      fieldUniversalIdentifier:
        COMMERCIAL_PROPOSAL_FIELD_IDEMPOTENCY_KEY_UNIVERSAL_IDENTIFIER,
    },
  ],
});

export const commercialProposalItemParentIndex = defineIndex({
  universalIdentifier:
    COMMERCIAL_PROPOSAL_ITEM_INDEX_PARENT_UNIVERSAL_IDENTIFIER,
  objectUniversalIdentifier: COMMERCIAL_PROPOSAL_ITEM_OBJECT_UNIVERSAL_IDENTIFIER,
  indexType: 'BTREE',
  fields: [
    {
      universalIdentifier: '13797096-584c-4071-8313-22db4fdf64e7',
      fieldUniversalIdentifier:
        COMMERCIAL_PROPOSAL_ITEM_FIELD_COMMERCIAL_PROPOSAL_UNIVERSAL_IDENTIFIER,
    },
  ],
});

export const commercialProposalItemClientKeyIndex = defineIndex({
  universalIdentifier:
    COMMERCIAL_PROPOSAL_ITEM_INDEX_CLIENT_KEY_UNIVERSAL_IDENTIFIER,
  objectUniversalIdentifier: COMMERCIAL_PROPOSAL_ITEM_OBJECT_UNIVERSAL_IDENTIFIER,
  indexType: 'BTREE',
  fields: [
    {
      universalIdentifier: '6e61b28e-a1da-46e3-9c34-7e9274eb791f',
      fieldUniversalIdentifier:
        COMMERCIAL_PROPOSAL_ITEM_FIELD_CLIENT_KEY_UNIVERSAL_IDENTIFIER,
    },
  ],
});

export const commercialProposalStageParentIndex = defineIndex({
  universalIdentifier:
    COMMERCIAL_PROPOSAL_STAGE_INDEX_PARENT_UNIVERSAL_IDENTIFIER,
  objectUniversalIdentifier:
    COMMERCIAL_PROPOSAL_STAGE_OBJECT_UNIVERSAL_IDENTIFIER,
  indexType: 'BTREE',
  fields: [
    {
      universalIdentifier: 'c75c264d-d9e4-4150-ae5f-0255f19e8fb6',
      fieldUniversalIdentifier:
        COMMERCIAL_PROPOSAL_STAGE_FIELD_COMMERCIAL_PROPOSAL_UNIVERSAL_IDENTIFIER,
    },
  ],
});

export const commercialProposalStageClientKeyIndex = defineIndex({
  universalIdentifier:
    COMMERCIAL_PROPOSAL_STAGE_INDEX_CLIENT_KEY_UNIVERSAL_IDENTIFIER,
  objectUniversalIdentifier:
    COMMERCIAL_PROPOSAL_STAGE_OBJECT_UNIVERSAL_IDENTIFIER,
  indexType: 'BTREE',
  fields: [
    {
      universalIdentifier: '0e4bbe40-f9ef-49af-8725-aa5d449891d8',
      fieldUniversalIdentifier:
        COMMERCIAL_PROPOSAL_STAGE_FIELD_CLIENT_KEY_UNIVERSAL_IDENTIFIER,
    },
  ],
});
