import { defineIndex } from 'twenty-sdk/define';
import { COMMERCIAL_PROPOSAL_STAGE_FIELD_CLIENT_KEY_UNIVERSAL_IDENTIFIER, COMMERCIAL_PROPOSAL_STAGE_INDEX_CLIENT_KEY_UNIVERSAL_IDENTIFIER, COMMERCIAL_PROPOSAL_STAGE_OBJECT_UNIVERSAL_IDENTIFIER } from 'src/constants/universal-identifiers';

export default defineIndex({
  universalIdentifier: COMMERCIAL_PROPOSAL_STAGE_INDEX_CLIENT_KEY_UNIVERSAL_IDENTIFIER,
  objectUniversalIdentifier: COMMERCIAL_PROPOSAL_STAGE_OBJECT_UNIVERSAL_IDENTIFIER,
  indexType: 'BTREE',
  fields: [{ universalIdentifier: '0e4bbe40-f9ef-49af-8725-aa5d449891d8', fieldUniversalIdentifier: COMMERCIAL_PROPOSAL_STAGE_FIELD_CLIENT_KEY_UNIVERSAL_IDENTIFIER }],
});
