import { defineObject, FieldType, RelationType } from 'twenty-sdk/define';

import {
  CATALOG_ITEM_FIELD_CATEGORY_UNIVERSAL_IDENTIFIER,
  CATALOG_ITEM_FIELD_CURRENCY_CODE_UNIVERSAL_IDENTIFIER,
  CATALOG_ITEM_FIELD_DEFAULT_BLOCK_UNIVERSAL_IDENTIFIER,
  CATALOG_ITEM_FIELD_DEFAULT_PRICE_UNIVERSAL_IDENTIFIER,
  CATALOG_ITEM_FIELD_DEFAULT_UNIT_UNIVERSAL_IDENTIFIER,
  CATALOG_ITEM_FIELD_DESCRIPTION_UNIVERSAL_IDENTIFIER,
  CATALOG_ITEM_FIELD_IS_ACTIVE_UNIVERSAL_IDENTIFIER,
  CATALOG_ITEM_FIELD_NAME_UNIVERSAL_IDENTIFIER,
  CATALOG_ITEM_FIELD_PRICE_UNIVERSAL_IDENTIFIER,
  CATALOG_ITEM_FIELD_PROPOSAL_ITEMS_UNIVERSAL_IDENTIFIER,
  CATALOG_ITEM_FIELD_SORT_ORDER_UNIVERSAL_IDENTIFIER,
  CATALOG_ITEM_FIELD_TYPE_UNIVERSAL_IDENTIFIER,
  CATALOG_ITEM_OBJECT_UNIVERSAL_IDENTIFIER,
  COMMERCIAL_PROPOSAL_ITEM_FIELD_CATALOG_ITEM_UNIVERSAL_IDENTIFIER,
  COMMERCIAL_PROPOSAL_ITEM_OBJECT_UNIVERSAL_IDENTIFIER,
} from 'src/constants/universal-identifiers';

export default defineObject({
  universalIdentifier: CATALOG_ITEM_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'catalogItem',
  namePlural: 'catalogItems',
  labelSingular: 'Позиция каталога',
  labelPlural: 'Каталог работ и услуг',
  description: 'Типовые позиции для добавления в коммерческие предложения',
  icon: 'IconLibrary',
  isSearchable: true,
  isUICreatable: true,
  isUIEditable: true,
  labelIdentifierFieldMetadataUniversalIdentifier:
    CATALOG_ITEM_FIELD_NAME_UNIVERSAL_IDENTIFIER,
  fields: [
    {
      universalIdentifier: CATALOG_ITEM_FIELD_NAME_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Наименование',
      description: 'Наименование типовой позиции',
      defaultValue: "''",
      isNullable: false,
    },
    {
      universalIdentifier: CATALOG_ITEM_FIELD_TYPE_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'itemType',
      label: 'Тип позиции',
      description: 'Коммерческая природа позиции: услуга, товар, лицензия, пакет или другое',
      defaultValue: "'SERVICE'",
      isNullable: false,
      options: [
        { position: 0, label: 'Услуга', value: 'SERVICE', color: 'blue' },
        { position: 1, label: 'Товар', value: 'PRODUCT', color: 'green' },
        { position: 2, label: 'Лицензия', value: 'LICENSE', color: 'purple' },
        { position: 3, label: 'Пакет', value: 'PACKAGE', color: 'yellow' },
        { position: 4, label: 'Другое', value: 'OTHER', color: 'gray' },
      ],
    },
    {
      universalIdentifier: CATALOG_ITEM_FIELD_CATEGORY_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'category',
      label: 'Категория каталога',
      description: 'Рубрика для поиска и фильтрации; в документ КП не копируется',
      defaultValue: null,
      isNullable: true,
    },
    {
      universalIdentifier: CATALOG_ITEM_FIELD_DEFAULT_BLOCK_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'defaultBlock',
      label: 'Блок работ в КП',
      description: 'Название раздела, которое копируется в строку и печатную форму КП',
      defaultValue: "'Работы'",
      isNullable: false,
    },
    {
      universalIdentifier: CATALOG_ITEM_FIELD_DESCRIPTION_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'description',
      label: 'Описание',
      description: 'Описание, копируемое в строку КП',
      defaultValue: null,
      isNullable: true,
      universalSettings: { displayedMaxRows: 4 },
    },
    {
      universalIdentifier: CATALOG_ITEM_FIELD_DEFAULT_UNIT_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'defaultUnit',
      label: 'Единица измерения',
      description: 'Единица измерения по умолчанию',
      defaultValue: "'час'",
      isNullable: false,
    },
    {
      universalIdentifier: CATALOG_ITEM_FIELD_PRICE_UNIVERSAL_IDENTIFIER,
      type: FieldType.CURRENCY,
      name: 'price',
      label: 'Цена',
      description: 'Цена за единицу и валюта',
      defaultValue: null,
      isNullable: true,
    },
    {
      universalIdentifier: CATALOG_ITEM_FIELD_DEFAULT_PRICE_UNIVERSAL_IDENTIFIER,
      type: FieldType.NUMBER,
      name: 'defaultPrice',
      label: 'Цена (legacy)',
      description: 'Устаревшая цена; сохранена для совместимости',
      defaultValue: 0,
      isNullable: false,
      isUIEditable: false,
      universalSettings: { decimals: 2 },
    },
    {
      universalIdentifier: CATALOG_ITEM_FIELD_CURRENCY_CODE_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'currencyCode',
      label: 'Валюта (legacy)',
      description: 'Устаревший ISO-код; сохранён для совместимости',
      defaultValue: "'RUB'",
      isNullable: false,
      isUIEditable: false,
    },
    {
      universalIdentifier: CATALOG_ITEM_FIELD_IS_ACTIVE_UNIVERSAL_IDENTIFIER,
      type: FieldType.BOOLEAN,
      name: 'isActive',
      label: 'Активна',
      description: 'Доступна для добавления в новые КП',
      defaultValue: true,
      isNullable: false,
    },
    {
      universalIdentifier: CATALOG_ITEM_FIELD_SORT_ORDER_UNIVERSAL_IDENTIFIER,
      type: FieldType.NUMBER,
      name: 'sortOrder',
      label: 'Порядок',
      description: 'Порядок позиции в результатах каталога',
      defaultValue: 100,
      isNullable: false,
      universalSettings: { decimals: 0 },
    },
    {
      universalIdentifier: CATALOG_ITEM_FIELD_PROPOSAL_ITEMS_UNIVERSAL_IDENTIFIER,
      type: FieldType.RELATION,
      name: 'proposalItems',
      label: 'Строки КП',
      description: 'Строки КП, первоначально созданные из позиции каталога',
      isNullable: true,
      relationTargetObjectMetadataUniversalIdentifier:
        COMMERCIAL_PROPOSAL_ITEM_OBJECT_UNIVERSAL_IDENTIFIER,
      relationTargetFieldMetadataUniversalIdentifier:
        COMMERCIAL_PROPOSAL_ITEM_FIELD_CATALOG_ITEM_UNIVERSAL_IDENTIFIER,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
  ],
});
